const express = require('express');
const router = express.Router();
const multer = require('multer');
const multerS3 = require('multer-s3');
const s3Client = require('../config/s3');
const { protect, admin } = require('../middleware/authMiddleware');

const BUCKET_NAME = process.env.MINIO_BUCKET_NAME || 'ecommerce-images';

const upload = multer({
  storage: multerS3({
    s3: s3Client,
    bucket: BUCKET_NAME,
    acl: 'public-read',
    metadata: function (req, file, cb) {
      cb(null, { fieldName: file.fieldname });
    },
    key: function (req, file, cb) {
      const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1e9);
      cb(null, 'products/' + uniqueSuffix + '-' + file.originalname);
    }
  })
});

// @desc    Upload product image to MinIO
// @route   POST /api/upload
// @access  Private/Admin
router.post('/', protect, admin, upload.single('image'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ message: 'No file uploaded' });
  }
  
  // The location URL generated by multer-s3 will point to http://localhost:9000/ecommerce-images/products/...
  res.json({
    message: 'Image uploaded successfully',
    url: req.file.location,
    filename: req.file.key
  });
});

module.exports = router;
