const express = require('express');
const router = express.Router();
const multer = require('multer');
const multerS3 = require('multer-s3');
const s3Client = require('../config/s3');
const { isAuth } = require('../middleware/isAuth');
const { isAdmin } = require('../middleware/isAdmin');

const BUCKET_NAME = process.env.MINIO_BUCKET_NAME || 'ecommerce-images';

const upload = multer({
  storage: multerS3({
    s3: s3Client,
    bucket: BUCKET_NAME,
    acl: 'public-read',
    metadata: function (req, file, cb) {
      cb(null, { fieldName: file.fieldname });
    },
    key: function (req, file, cb) {
      const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1e9);
      cb(null, 'products/' + uniqueSuffix + '-' + file.originalname);
    }
  })
});

// @desc    Upload product image to MinIO
// @route   POST /api/upload
// @access  Private/Admin
router.post('/', isAuth, isAdmin, upload.single('image'), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ message: 'No file uploaded' });
  }
  
  // The location URL generated by multer-s3 will point to http://localhost:9000/ecommerce-images/products/...
  let imageUrl = req.file.location;
  // If the URL contains the docker internal hostname (minio), replace it with localhost for the frontend to access
  if (imageUrl.includes('http://minio:9000')) {
    imageUrl = imageUrl.replace('http://minio:9000', 'http://localhost:9000');
  }

  res.json({
    message: 'Image uploaded successfully',
    url: imageUrl,
    filename: req.file.key
  });
});

module.exports = router;
